spring:
  application:
    name: liber

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    url: jdbc:postgresql://localhost:5432/liber_db
    username: liber
    password: liber
